---
- name: Install Python on a newly provisioned machine 
  gather_facts: no
  become: true
  hosts: all
  roles:
    - { role: python-installer }

- name: Install & configure SSH on servers
  gather_facts: yes
  sudo: yes
  hosts: default
  roles:
    - { role: ssh-devops,   tags: ['ssh-user'] }
    - { role: sys-manager,  tags: ['ssh-user'] }