---
- name: Install & configure SSH on servers
  gather_facts: True
  sudo: yes
  hosts: default
  roles:
    - { role: ssh-devops,   tags: ['ssh-user'] }
#    - { role: sys-manager,  tags: ['ssh-user'] }